Do a more explicit / module-by-module checkout rather than a single run (which uses more cvs server resources & dies).
* www/tinder-scripts/tinder-build (checkout_source),
(checkout_complete): do a more explicit / module-by-module
checkout rather than a single run (which uses more cvs
server resources & dies).

diff --git a/www/tinder-scripts/tinder-build b/www/tinder-scripts/tinder-build
--- a/www/tinder-scripts/tinder-build
+++ b/www/tinder-scripts/tinder-build
@@ -25,33 +25,39 @@ $COMMON_CONFIGURE_OPTIONS=
 
 $CONFIGURE_OPTIONS = "$COMMON_CONFIGURE_OPTIONS $CONFIGURE_OPTIONS";
 
-$BUILD_DIR = '/tmp/tinder';
+$WORK_DIR = '/tmp/tinder';
+$BUILD_DIR = $WORK_DIR.'/build';
 $BUILD_NCPUS = 1;
-$BUILDNAME = 'NLD9/gcc33(x86)'; # best if it includes the OS etc.
+$BUILDNAME = 'NLD9-gcc33(x86)'; # best if it includes the OS etc.
 $MAINTAINER = 'Michael Meeks <michael.meeks@novell.com>';
 $BUILD_OS = 'NLD 9';
 $DEFAULT_CVSROOT = ':pserver:anoncvs@anoncvs.services.openoffice.org:/cvs';
 
 # All for broken mozilla foo
-$BUILD_SRC = '/share/src';
+$BUILD_SRC = $WORK_DIR.'/src';
 $MOZILLA_SRC = 'mozilla-source-1.7.5.tar.gz';
 $MOZILLA_URL = 'http://ftp.mozilla.org/pub/mozilla.org/mozilla/releases/mozilla1.7.5/source/';
 
+# cvs compression level
+$CVS_COMPRESS = '-z5';
+
 # -- debug tweaks --
-my $debug = 1;
+my $debug = 0;
 my $shortcircuit_checkout = 0;
-my $shortcircuit_clean = 0;
+my $shortcircuit_pre_clean = 0;
 my $shortcircuit_build = 0;
 
 # -- Things not to tweak --
 $BUILD_TAG_BASE = 'http://go-oo.org/tinderbox/tags/';
 $BUILD_TAG_NAME = 'tag-list';
-$TINDER_DEST = 'ooo@go-oo.org';
-$SENDMAIL = '/usr/sbin/sendmail';
+# $TINDER_DEST = 'ooo@go-oo.org';
+$TINDER_DEST = 'ooo@ooo.ximian.com';
+# My odd chroot jail setup:
+$MTA = 'ssh localhost /usr/bin/mail';
+# Something more sane:
+# $MTA = '/usr/bin/mail';
 $LOGDIR = $ENV{'HOME'} . "/build-logs";
 `mkdir -p $LOGDIR`;
-
--X $SENDMAIL || die "No sendmail";
 
 sub log_msg($@)
 {
@@ -92,7 +98,7 @@ sub start_mail($$$)
 	if( $debug ) {
 	    $MAIL = STDERR;
 	} else {
-	    open ($MAIL, "|$SENDMAIL $TINDER_DEST") || die "Can't send mail";
+	    open ($MAIL, "|$MTA -s 'tinder log' $TINDER_DEST") || die "Can't send mail";
 	}
 	print $MAIL $MAIL_HEADER;
 
@@ -149,6 +155,41 @@ sub cvs_op($$$)
     }
 }
 
+# the anoncvs server just dies if you try a complete checkout
+sub checkout_complete($$)
+{
+    my $master_tag = shift;
+    my $log = shift;
+
+    log_msg ($log, "Start complete checkout of $master_tag\n");
+    
+    my $CvsRoot;
+    my @modules = ();
+    my $reading_modules = 0;
+    open ($CvsRoot, "cvs $CVS_COMPRESS co -c 2>&1 | tee -a $log |") || return 0;
+    while (<$CvsRoot>) {
+	$reading_modules = 0 if (/^\S/);
+	$reading_modules = '1' if (/^OpenOffice2\s+\-a\s+/);
+	if ($reading_modules) {
+	    chomp;
+	    s/^.*\-a//;
+	    for my $elem (split (/ +/, $_)) {
+		push @modules, $elem if ($elem ne '');
+	    }
+	}
+    }
+    close ($CvsRoot) || return 0;
+
+    for my $mod (@modules) {
+	print "Module '$mod'\n";
+	cvs_op ("checkout -r $master_tag $mod", '.', $log) || return 0;
+    }
+
+    log_msg ($log, "Completed checkout of $master_tag\n");
+
+    return 1;
+}
+
 sub checkout_source($$)
 {
     my $cws = shift;
@@ -168,9 +209,14 @@ sub checkout_source($$)
     my $cws_branch_tag = $cws->{'cws_tag'};
     my $master_milestone_tag = $cws->{'master_tag'};
 
-    cvs_op ("checkout -r $master_milestone_tag OpenOffice", '', $log) || return 0;
+    checkout_complete ($master_milestone_tag, $log) || return 0;
 
-    for $module (@modules) {
+#    unfortunately this fails ...
+#    cvs_op ("checkout -r $master_milestone_tag OpenOffice", '', $log) || return 0;
+
+    log_msg ($log, "Start update of modules to $cws_branch_tag\n");
+
+    for my $module (@modules) {
 	if (! -d "$BUILD_DIR/$module") {
 	    log_msg ($log, "ERROR: missing module $module: no directory to update to $cws_branch_tag\n");
 	    return 0;
@@ -272,7 +318,7 @@ export TERM=
 unset MAKEFLAGS
 
 # Accelerate straight-through compiles by not building / using dependencies
-export nodep=1
+# export nodep=1 - FIXME: make conditional on shortcircuit_pre_clean setting
 echo "Env:"
 set
 
@@ -300,9 +346,9 @@ sub build_one {
     $MAIL = start_mail ('building', $tree, $starttime);
     end_mail ($MAIL);
 
-    if (($shortcircuit_checkout || checkout_source ($cws, $buildlog)) &&
-	($shortcircuit_clean || clean_source ($tree, $buildlog)) &&
-	($shortcircuit_build || build_source ($tree, $buildlog)) ) {
+    if (($shortcircuit_checkout  || checkout_source ($cws, $buildlog)) &&
+	($shortcircuit_pre_clean || clean_source ($tree, $buildlog)) &&
+	($shortcircuit_build     || build_source ($tree, $buildlog)) ) {
 	$status = 'success';
     } else {
 	$status = 'build_failed';
@@ -328,6 +374,10 @@ sub get_cws_with_state($)
 #    print STDERR "CWS list [$DEFAULT_MASTER] : @list\n";
 
     return @list;
+}
+
+if ($BUILDNAME =~ m/[\/!|~\#\?\>\<]/) {
+    print "Invalid build name '$BUILDNAME'\n";
 }
 
 if (! -f "$BUILD_SRC/$MOZILLA_SRC") {
